"""Add todo fields

Revision ID: 4aa740575f88
Revises: 
Create Date: 2024-07-12 10:32:10.116184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa740575f88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom_edition', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('type_edition', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('type_envoie', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('nombre_page_destinataire', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('nombre_destinataires', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('nombre_page', sa.Integer(), nullable=False))
        batch_op.drop_column('completed')
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('completed', sa.INTEGER(), nullable=True))
        batch_op.drop_column('nombre_page')
        batch_op.drop_column('nombre_destinataires')
        batch_op.drop_column('nombre_page_destinataire')
        batch_op.drop_column('type_envoie')
        batch_op.drop_column('type_edition')
        batch_op.drop_column('nom_edition')

    # ### end Alembic commands ###
